# Generated by Django 6.0.6 on 2026-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Pending', max_length=20),
        ),
    ]
