# Generated by Django 6.0.6 on 2026-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
