# Generated by Django 6.0.6 on 2026-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
