# Generated by Django 6.0.6 on 2026-07-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_certifications_application_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('Google Meet', 'Google Meet'), ('Zoom', 'Zoom'), ('Offline', 'Offline')], max_length=50),
        ),
    ]
