# Generated by Django 6.0.6 on 2026-07-09 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_created_at_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
