# Generated by Django 6.0.6 on 2026-07-06 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='recruiter/profile/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email_notification', models.BooleanField(default=True)),
                ('resume_notification', models.BooleanField(default=True)),
                ('interview_notification', models.BooleanField(default=True)),
                ('offer_notification', models.BooleanField(default=True)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('minimum_score', models.IntegerField(default=70)),
                ('default_skills', models.TextField(blank=True)),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Blue', 'Blue'), ('Green', 'Green')], default='Light', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
