# Generated by Django 6.0.6 on 2026-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_recruitersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitersettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='recruitersettings',
            name='minimum_score',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='recruitersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='recruitersettings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
