# Generated by Django 6.0.6 on 2026-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_recruitersettings_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitersettings',
            name='dashboard_color',
            field=models.CharField(choices=[('Default', 'Default'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Green', 'Green')], default='Default', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitersettings',
            name='font_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitersettings',
            name='gemini_api_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitersettings',
            name='openai_api_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitersettings',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitersettings',
            name='sidebar_color',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Dark', 'Dark'), ('Success', 'Success'), ('Danger', 'Danger')], default='Primary', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recruitersettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logo/'),
        ),
        migrations.AlterField(
            model_name='recruitersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitersettings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter/profile/'),
        ),
    ]
