# Generated by Django 6.0.6 on 2026-07-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_alter_interview_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitersettings',
            name='ai_enabled',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='dashboard_color',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='default_skills',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='email_notification',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='interview_notification',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='minimum_score',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='offer_notification',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='resume_notification',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='sidebar_color',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='recruitersettings',
            name='user',
        ),
    ]
