# Generated by Django 6.0.6 on 2026-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
