# Generated by Django 6.0.6 on 2026-07-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
    ]
