# Generated by Django 6.0.6 on 2026-07-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
    ]
